scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: 
         - 'otel_collector:8888'
         - 'otel_collector:8889'
  - job_name: 'application'
    scrape_interval: 10s
    static_configs:
      - targets: ['ge_chatapp:8080']