{
 "title": "Image Information",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Error Logs From Redundancy Service",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{job=\"ChatAppConsole\", level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "Percentage of Backed up Photos",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expression": "($A/$B) * 100", "reducer": "mean", "type": "math" }
   ]
  },
  {
   "title": "Messages Containing Images",
   "type": "traces",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "query": "ac436ac7f67f2a5bdaa592231020f99f"
    }
   ]
  },
  {
   "title": "Message With Image vs Without",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(messages_count_total{job=\"application\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(message_with_image_total{job=\"application\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request/Response Times",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(http_server_request_duration_seconds_sum{http_route=\"api/Chat\", job=\"application\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}