version: '3.8'

x-raftnode-base: &raftnode_base
    build:
        context: ./../../ 
        dockerfile: 'Raft_Node/Dockerfile'
    restart: always
    
x-raftnode-env: &raftnode_env
    TZ: America/Denver
    aspnetcore_environment: Development
    COLLECTORURL: 'http://garrett_otel_collector:4317'
    ASPNETCORE_URLS: http://+:8080
    ApiOptions__NodeCount: 3
    ApiOptions__NodeServiceName: raftnode
    ApiOptions__NodeServicePort: 8080
    ApiOptions__LogMessageIntervalSeconds: 30 


services: 
    raftnode1:
        <<: *raftnode_base
        container_name: garrett_raftnode1
        environment: 
            <<: *raftnode_env
            NodeIdentifier: 1
        profiles:
            - manager
        networks:
            - g-overlay-worker
    raftnode2:
        <<: *raftnode_base
        container_name: garrett_raftnode2
        environment: 
            <<: *raftnode_env
            NodeIdentifier: 2
        profiles:
            - manager
        networks:
            - g-overlay
    raftnode3:
        <<: *raftnode_base
        container_name: garrett_raftnode3
        environment: 
            <<: *raftnode_env
            NodeIdentifier: 3
        profiles:
            - worker
        networks:
            - g-overlay-worker

    garrett_gateway: 
        container_name: garrett_gateway
        build:
            context: ./../../ 
            dockerfile: 'Raft_Gateway/Dockerfile'
        restart: always
        environment:
            TZ: America/Denver
            COLLECTORURL: 'http://garrett_otel_collector:4317'
            aspnetcore_environment: Development
        profiles:
          - manager
        networks:
          - g-overlay
            
    garrrett_swag:
        image: lscr.io/linuxserver/swag
        container_name: garrett_Raftshop_proxy
        cap_add:
            - NET_ADMIN
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=America/Denver
            - URL=shopraft.duckdns.org
            - VALIDATION=duckdns
            - DUCKDNSTOKEN=${DUCKDNSTOKEN}
            - STAGING=false
        volumes:
            - /home/garrett/data/swag:/config
            - ./swag-default.conf:/config/nginx/site-confs/default.conf
        ports:
            - 0.0.0.0:1460:443
        restart: always
        profiles:
          - manager
        networks:
          - g-overlay

    garrett_shop:
        container_name: garrett_shop
        build:
            context: ./../../ 
            dockerfile: 'Raft_Shop/Raft_Shop/Dockerfile'
        environment:
            TZ: America/Denver
            COLLECTORURL: 'http://otel_collector:4317'
            aspnetcore_environment: Development
            GatewayAddress: 'http://garrett_gateway:8080'
        depends_on:
            - swag
        profiles:
          - manager
        networks:
          - g-overlay

    garrett_otel_collector:
        image: otel/opentelemetry-collector-contrib
        container_name: garrett_otel_collector
        restart: always
        volumes:
            - ./configs/otel-collector-config.yml:/etc/otelcol-contrib/config.yml
        networks:
          - g-overlay

    garrett_zipkin:
        image: ghcr.io/openzipkin/zipkin-slim:${TAG:-latest}
        container_name: garrett_zipkin
        restart: always
        # Environment settings are defined here https://github.com/openzipkin/zipkin/blob/master/zipkin-server/README.md#environment-variables
        environment:
            - STORAGE_TYPE=mem
        # ports:
        #   # Port used for the Zipkin UI and HTTP Api
        #   - 9411:9411
        networks:
            - g-overlay

    garrett_prometheus:
        image: prom/prometheus
        container_name: garrett_prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
        # ports:
        #   - 9090:9090
        restart: always
        volumes:
            - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
        networks:
            - g-overlay
    garrett_grafana:
        build:
            context: .
            dockerfile: ./Dockerfiles/grafana/Dockerfile
        user: "1001"
        container_name: garrett_grafana
        # ports:
            # - 3000:3000
        restart: always
        environment:
            - GF_SECURITY_ADMIN_USER=notadmin
            - GF_SECURITY_ADMIN_PASSWORD=notpassword
        volumes:
            - ./configs/grafana-dashboards.yml:/etc/grafana/provisioning/dashboards/default.yml
            - ./dashboards:/var/lib/grafana/dashboards
            - ./configs/datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml
            - ./configs/grafana.ini:/etc/grafana/grafana.ini
        networks:
            - g-overlay
    garrett_loki:
        image: grafana/loki:2.9.0
        command: -config.file=/etc/loki/local-config.yml
        container_name: garrett_loki
        restart: always
        volumes:
            - ./configs/loki.yml:/etc/loki/local-config.yml
        # ports:
        #   - "3100:3100"
        networks:
            - g-overlay

networks:
  g-overlay:
    name: g-overlay
    driver: overlay
    attachable: true
  g-overlay-worker:
    name: g-overlay
    driver: overlay
    external: true